# Generated by Django 4.2.7 on 2023-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('usuario', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('mensaje', models.TextField(max_length=200)),
            ],
        ),
    ]
